### ISSUE TITLE
Readthedoc is not building the doc

### ISSUE THREAD

**Issue by glemaitre** [joblib/joblib#622]
With have issue building the doc:

https://readthedocs.org/projects/joblib/builds/

I think that we have at least the following issues:

* issues with the link to the `png` logo for the example. ping @aabadie 
* On the last log, it seems that the notebook associated to `memory_usage` has not been created but difficult to say if this is just a side effect.

**Comment by aabadie** [comment]
Just had a brief look at this and I think readthedocs is perhaps not generating the documentation using `python setup.py build_sphinx` from the joblib source base directory but rather using `sphinx-build` from the `doc` directory.
If I use the former, everything works well but if I use the latter, I have the issue with the logo file not found. In `conf.py`, changing `'default_thumb_file': 'doc/_static/joblib_logo_examples.png'` to `'default_thumb_file': '_static/joblib_logo_examples.png'` (line 50) works with the latter (but then not with the former).

The problem with memory_usage example seems to be related to `auto_examples` caching. After the error with the logo, this one fails but after removing the examples cache and fixing the logo path, it works again.

Regarding the logo, a potential quick fix could be to use `doc/_static/logo.png` if it exists and if not, use `_static/logo.png` instead.

What do you think ?

**Comment by glemaitre** [comment]
can we have a `Makefile` and a `make.bat` which run `sphinx-build` from `doc`. Not sure what is the simplest.

**Comment by GaelVaroquaux** [comment]
> can we have a Makefile and a make.bat which run sphinx-build from doc.

Let's do this!

Someone wants to submit a PR with that.

**Comment by GaelVaroquaux** [comment]
Actually, ... do people know how to have external dependencies for building on read-the-docs? I am asking because if we cannot have such dependencies, we might need to move away from read-the-docs.

**Comment by aabadie** [comment]
> Someone wants to submit a PR with that

I can do that ;)

**Comment by GaelVaroquaux** [comment]
> I can do that ;)

Thanks!!! But first we need to decide if we stay on rtd: we need to be
able to have additional dependencies to build the docs.

**Comment by glemaitre** [comment]
> Actually, ... do people know how to have external dependencies for building on read-the-docs? I am asking because if we cannot have such dependencies, we might need to move away from read-the-docs.

You can always add the dependencies ins the `.readthedoc-requirements.txt`. What ever is pip installable will be fine (pypi package, and github)

**Comment by GaelVaroquaux** [comment]
Ok. That's good enough !

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by aabadie** [comment]
Done, see #623

**Comment by GaelVaroquaux** [comment]
RTD is still failing. It would need a clean restart, flushing the files.

Someone knows how to do this?

**Comment by aabadie** [comment]
> Someone knows how to do this?

This is explained [here](http://docs.readthedocs.io/en/latest/builds.html#deleting-a-stale-or-broken-build-environment). But I don't see the 'Wipe' button on the mentioned page.

**Comment by GaelVaroquaux** [comment]
I think that we don't see this button because we need admin rights on the project. But I don't know how to retrieve them. I've successfully connected my github account to RTD, but...

**Comment by GaelVaroquaux** [comment]
OK, @lesteve  is the sole owner of the RTD project: https://readthedocs.org/projects/joblib/

When he comes back from week end we will have to ask him to add people.

**Comment by aabadie** [comment]
It's probably like on pypi, the person who created the project should invite/grant someelse's account.

**Comment by lesteve** [comment]
I think you need to create a readthedocs account and then I can add you as maintainer.

**Comment by lesteve** [comment]
I wiped (found a link [here](https://readthedocs.org/dashboard/joblib/version/latest/) at the bottom) and triggered a new build.

**Comment by glemaitre** [comment]
Seems to work!

**Comment by aabadie** [comment]
Yeah, thanks @lesteve !

**Comment by GaelVaroquaux** [comment]
> I think you need to create a readthedocs account and then I can add you as maintainer.

I have one: GaelVaroquaux

**Comment by lesteve** [comment]
@GaelVaroquaux you should be a maintainer now.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux you should be a maintainer now.

Indeed. Thanks! @aabadie, @ogrisel, it might be good to add you too. If
you create an account, we'll do that.

**Comment by aabadie** [comment]
I have : aabadie

**Comment by lesteve** [comment]
Done
