### ISSUE TITLE
Lower prediction speed after Version 0.14.0

### ISSUE THREAD

**Issue by Zarkxxxxx** [joblib/joblib#982]
Hi there.i found that the model predict speed will getting lower after i update joblib version from 0.13.0 to 0.14.0.i have tried several time between the version from 0.13.0 to 0.14.0,but get the same result. 

the model used Avg 0.01s to predict the reult before version 0.14.0,but used Avg 0.10s  after version 0.14.0.(i have tried several different model and the same result.btw,the model all training in version 0.13)

another change is that, i will get a userwarning 
" UserWarning: Loky-backed parallel loops cannot be nested below threads, setting n_jobs=1
  n_jobs = effective_n_jobs(self.n_jobs)"
before version 0.14.0 when i ask model predicting.this warning seem be repaired after version 0.14.0.
Does this revision affect the prediction speed？: )

**Comment by ogrisel** [comment]
We released joblib 0.14.1 with fixes for performance regression. Can you please check if they fix your problem? https://github.com/joblib/joblib/blob/master/CHANGES.rst#release-0141

**Comment by Zarkxxxxx** [comment]
@ogrisel Thank you for your reply XD.I have tried 0.14.1,but the problem still there.And i found the main differences between 0.14.x and 0.13.x(or berfore) is the prediction time,the time of model loding is nearly same.

**Comment by tomMoral** [comment]
Would you have a small script reproducing this benchmark? This would help us a lot in pinning down where this regression could come from.

**Comment by Zarkxxxxx** [comment]
@ogrisel @tomMoral 
Thank you for your reply.I make a simple test to compare two version,and i find the problem.

I use a RandomForestRegressor to test,so that i can change model parameters and run in parallel.
I also tested the running in the thread(status in my work before)

In my opinion,n_jobs userwarning before 0.14.x make the model predict in n_jobs=1.After this problem repaired,model can predict n_jobs=-1 in 0.14.x.
but the problem is why jobs to run in parallel make prediction speed slower?

here is the result:
![image](https://user-images.githubusercontent.com/49779428/71913598-c35fda00-31b2-11ea-9b01-9ae121d52b43.png)

and here is the test code:
<details>
<summary>test code</summary>

```python
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
import numpy as np
import time
import joblib
from threading import Thread

#data create

#as a sample,i use sklearn to create regression
n_features = 5
x, y = make_regression(n_samples=1000, n_features=n_features, noise=0.2)

#create model with pipeline
model_pipeline = Pipeline([('Scaler', StandardScaler()),('model',RandomForestRegressor(n_estimators=100,n_jobs=-1))])

#traning the model
model_pipeline.fit(x,y)

#test original predict time for 10 times
predict_data = [1 for i in range(n_features)]
time_list = np.array([])

for _ in (range(10)):
    start_time = time.time()
    model_pipeline.predict([predict_data])
    end_time = time.time()
    time_list = np.append(time_list,end_time-start_time)
    print('original predict time: ',end_time-start_time)

print('average original predict time:',time_list.mean())

#save model
joblib.dump(model_pipeline,'test.pkl')
del model_pipeline

#load model
model_pipeline = joblib.load('test.pkl')

#test reload predict time for 10 times
predict_data = [1 for i in range(n_features)]
time_list = np.array([])

for _ in (range(10)):
    start_time = time.time()
    model_pipeline.predict([predict_data])
    end_time = time.time()
    time_list = np.append(time_list,end_time-start_time)
    print('reload predict time: ',end_time-start_time)

print('average reload predict time:',time_list.mean())
del model_pipeline

#test with thread
def thread_def():
    n_features=5

    #load model
    model_pipeline = joblib.load('test.pkl')

    #test reload predict time for 10 times
    predict_data = [1 for i in range(n_features)]
    time_list = np.array([])

    for _ in (range(10)):
        start_time = time.time()
        model_pipeline.predict([predict_data])
        end_time = time.time()
        time_list = np.append(time_list,end_time-start_time)
        print('thread reload predict time: ',end_time-start_time)

    print('average thread reload predict time:',time_list.mean())

thread = Thread(target=thread_def)
thread.start()
thread.join()
```
</details>

**Comment by tomMoral** [comment]
Hi!

Thanks for the reproducing script. Yes this is known issue with `RandomForestRegressor` and I open an issue to track this down in `scikit-learn`. If `n_jobs > 1`, the prediction for the regressor on a small batch (here you have a batch on 1 prediction) is slow as the time to create threads dominate the runtime compared to the time of computing the results. There is no good answer to this at the moment.

In the mean time, to mitigate this issue, you could simply set `n_jobs=1` in your model once it has been trained.
